// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/sidebar/': RouteRecordInfo<'/sidebar/', '/sidebar', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards': RouteRecordInfo<'/sidebar/dashboards', '/sidebar/dashboards', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/': RouteRecordInfo<'/sidebar/dashboards/', '/sidebar/dashboards', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/analytics': RouteRecordInfo<'/sidebar/dashboards/analytics', '/sidebar/dashboards/analytics', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/banking-1': RouteRecordInfo<'/sidebar/dashboards/banking-1', '/sidebar/dashboards/banking-1', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/banking-2': RouteRecordInfo<'/sidebar/dashboards/banking-2', '/sidebar/dashboards/banking-2', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/banking-3': RouteRecordInfo<'/sidebar/dashboards/banking-3', '/sidebar/dashboards/banking-3', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/charts-apex': RouteRecordInfo<'/sidebar/dashboards/charts-apex', '/sidebar/dashboards/charts-apex', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/charts-billboardsjs': RouteRecordInfo<'/sidebar/dashboards/charts-billboardsjs', '/sidebar/dashboards/charts-billboardsjs', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/company': RouteRecordInfo<'/sidebar/dashboards/company', '/sidebar/dashboards/company', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/course': RouteRecordInfo<'/sidebar/dashboards/course', '/sidebar/dashboards/course', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/ecommerce-1': RouteRecordInfo<'/sidebar/dashboards/ecommerce-1', '/sidebar/dashboards/ecommerce-1', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/flights': RouteRecordInfo<'/sidebar/dashboards/flights', '/sidebar/dashboards/flights', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/food-delivery': RouteRecordInfo<'/sidebar/dashboards/food-delivery', '/sidebar/dashboards/food-delivery', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/health': RouteRecordInfo<'/sidebar/dashboards/health', '/sidebar/dashboards/health', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/hobbies': RouteRecordInfo<'/sidebar/dashboards/hobbies', '/sidebar/dashboards/hobbies', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/human-ressources': RouteRecordInfo<'/sidebar/dashboards/human-ressources', '/sidebar/dashboards/human-ressources', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/influencer': RouteRecordInfo<'/sidebar/dashboards/influencer', '/sidebar/dashboards/influencer', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/jobs': RouteRecordInfo<'/sidebar/dashboards/jobs', '/sidebar/dashboards/jobs', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/personal-2': RouteRecordInfo<'/sidebar/dashboards/personal-2', '/sidebar/dashboards/personal-2', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/personal-3': RouteRecordInfo<'/sidebar/dashboards/personal-3', '/sidebar/dashboards/personal-3', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/sales': RouteRecordInfo<'/sidebar/dashboards/sales', '/sidebar/dashboards/sales', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/soccer': RouteRecordInfo<'/sidebar/dashboards/soccer', '/sidebar/dashboards/soccer', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/stocks': RouteRecordInfo<'/sidebar/dashboards/stocks', '/sidebar/dashboards/stocks', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/video': RouteRecordInfo<'/sidebar/dashboards/video', '/sidebar/dashboards/video', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/widgets-sample-creative': RouteRecordInfo<'/sidebar/dashboards/widgets-sample-creative', '/sidebar/dashboards/widgets-sample-creative', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/widgets-sample-list': RouteRecordInfo<'/sidebar/dashboards/widgets-sample-list', '/sidebar/dashboards/widgets-sample-list', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/widgets-sample-stats': RouteRecordInfo<'/sidebar/dashboards/widgets-sample-stats', '/sidebar/dashboards/widgets-sample-stats', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/widgets-sample-ui': RouteRecordInfo<'/sidebar/dashboards/widgets-sample-ui', '/sidebar/dashboards/widgets-sample-ui', Record<never, never>, Record<never, never>>,
    '/sidebar/dashboards/writer': RouteRecordInfo<'/sidebar/dashboards/writer', '/sidebar/dashboards/writer', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts': RouteRecordInfo<'/sidebar/layouts', '/sidebar/layouts', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/': RouteRecordInfo<'/sidebar/layouts/', '/sidebar/layouts', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/action-page-1': RouteRecordInfo<'/sidebar/layouts/action-page-1', '/sidebar/layouts/action-page-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/action-page-2': RouteRecordInfo<'/sidebar/layouts/action-page-2', '/sidebar/layouts/action-page-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/form-layouts-1': RouteRecordInfo<'/sidebar/layouts/form-layouts-1', '/sidebar/layouts/form-layouts-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/form-layouts-2': RouteRecordInfo<'/sidebar/layouts/form-layouts-2', '/sidebar/layouts/form-layouts-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/form-layouts-3': RouteRecordInfo<'/sidebar/layouts/form-layouts-3', '/sidebar/layouts/form-layouts-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/form-layouts-4': RouteRecordInfo<'/sidebar/layouts/form-layouts-4', '/sidebar/layouts/form-layouts-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/form-layouts-5': RouteRecordInfo<'/sidebar/layouts/form-layouts-5', '/sidebar/layouts/form-layouts-5', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-cards-1': RouteRecordInfo<'/sidebar/layouts/grid-cards-1', '/sidebar/layouts/grid-cards-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-cards-2': RouteRecordInfo<'/sidebar/layouts/grid-cards-2', '/sidebar/layouts/grid-cards-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-cards-3': RouteRecordInfo<'/sidebar/layouts/grid-cards-3', '/sidebar/layouts/grid-cards-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-cards-4': RouteRecordInfo<'/sidebar/layouts/grid-cards-4', '/sidebar/layouts/grid-cards-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-tiles-1': RouteRecordInfo<'/sidebar/layouts/grid-tiles-1', '/sidebar/layouts/grid-tiles-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-tiles-2': RouteRecordInfo<'/sidebar/layouts/grid-tiles-2', '/sidebar/layouts/grid-tiles-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-tiles-3': RouteRecordInfo<'/sidebar/layouts/grid-tiles-3', '/sidebar/layouts/grid-tiles-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-users-1': RouteRecordInfo<'/sidebar/layouts/grid-users-1', '/sidebar/layouts/grid-users-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-users-2': RouteRecordInfo<'/sidebar/layouts/grid-users-2', '/sidebar/layouts/grid-users-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-users-3': RouteRecordInfo<'/sidebar/layouts/grid-users-3', '/sidebar/layouts/grid-users-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/grid-users-4': RouteRecordInfo<'/sidebar/layouts/grid-users-4', '/sidebar/layouts/grid-users-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/kanban-board': RouteRecordInfo<'/sidebar/layouts/kanban-board', '/sidebar/layouts/kanban-board', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-datatable-1': RouteRecordInfo<'/sidebar/layouts/list-datatable-1', '/sidebar/layouts/list-datatable-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-datatable-2': RouteRecordInfo<'/sidebar/layouts/list-datatable-2', '/sidebar/layouts/list-datatable-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-datatable-3': RouteRecordInfo<'/sidebar/layouts/list-datatable-3', '/sidebar/layouts/list-datatable-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-datatable-4': RouteRecordInfo<'/sidebar/layouts/list-datatable-4', '/sidebar/layouts/list-datatable-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-flex-1': RouteRecordInfo<'/sidebar/layouts/list-flex-1', '/sidebar/layouts/list-flex-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-flex-2': RouteRecordInfo<'/sidebar/layouts/list-flex-2', '/sidebar/layouts/list-flex-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-flex-3': RouteRecordInfo<'/sidebar/layouts/list-flex-3', '/sidebar/layouts/list-flex-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-view-2': RouteRecordInfo<'/sidebar/layouts/list-view-2', '/sidebar/layouts/list-view-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-view-3': RouteRecordInfo<'/sidebar/layouts/list-view-3', '/sidebar/layouts/list-view-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/list-view-4': RouteRecordInfo<'/sidebar/layouts/list-view-4', '/sidebar/layouts/list-view-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-page-1': RouteRecordInfo<'/sidebar/layouts/onboarding-page-1', '/sidebar/layouts/onboarding-page-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-page-2': RouteRecordInfo<'/sidebar/layouts/onboarding-page-2', '/sidebar/layouts/onboarding-page-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-page-3': RouteRecordInfo<'/sidebar/layouts/onboarding-page-3', '/sidebar/layouts/onboarding-page-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-page-4': RouteRecordInfo<'/sidebar/layouts/onboarding-page-4', '/sidebar/layouts/onboarding-page-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-page-5': RouteRecordInfo<'/sidebar/layouts/onboarding-page-5', '/sidebar/layouts/onboarding-page-5', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/onboarding-welcome': RouteRecordInfo<'/sidebar/layouts/onboarding-welcome', '/sidebar/layouts/onboarding-welcome', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/placeload-1': RouteRecordInfo<'/sidebar/layouts/placeload-1', '/sidebar/layouts/placeload-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/placeload-2': RouteRecordInfo<'/sidebar/layouts/placeload-2', '/sidebar/layouts/placeload-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/placeload-3': RouteRecordInfo<'/sidebar/layouts/placeload-3', '/sidebar/layouts/placeload-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/placeload-4': RouteRecordInfo<'/sidebar/layouts/placeload-4', '/sidebar/layouts/placeload-4', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-edit': RouteRecordInfo<'/sidebar/layouts/profile-edit', '/sidebar/layouts/profile-edit', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-edit/': RouteRecordInfo<'/sidebar/layouts/profile-edit/', '/sidebar/layouts/profile-edit', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-edit/[id]': RouteRecordInfo<'/sidebar/layouts/profile-edit/[id]', '/sidebar/layouts/profile-edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/sidebar/layouts/profile-edit/experience': RouteRecordInfo<'/sidebar/layouts/profile-edit/experience', '/sidebar/layouts/profile-edit/experience', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-edit/settings': RouteRecordInfo<'/sidebar/layouts/profile-edit/settings', '/sidebar/layouts/profile-edit/settings', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-edit/skills': RouteRecordInfo<'/sidebar/layouts/profile-edit/skills', '/sidebar/layouts/profile-edit/skills', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-notifications': RouteRecordInfo<'/sidebar/layouts/profile-notifications', '/sidebar/layouts/profile-notifications', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-settings': RouteRecordInfo<'/sidebar/layouts/profile-settings', '/sidebar/layouts/profile-settings', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/profile-view': RouteRecordInfo<'/sidebar/layouts/profile-view', '/sidebar/layouts/profile-view', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/projects-details': RouteRecordInfo<'/sidebar/layouts/projects-details', '/sidebar/layouts/projects-details', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/projects-projects-1': RouteRecordInfo<'/sidebar/layouts/projects-projects-1', '/sidebar/layouts/projects-projects-1', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/projects-projects-2': RouteRecordInfo<'/sidebar/layouts/projects-projects-2', '/sidebar/layouts/projects-projects-2', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/projects-projects-3': RouteRecordInfo<'/sidebar/layouts/projects-projects-3', '/sidebar/layouts/projects-projects-3', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/saas-billing': RouteRecordInfo<'/sidebar/layouts/saas-billing', '/sidebar/layouts/saas-billing', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/search-empty': RouteRecordInfo<'/sidebar/layouts/search-empty', '/sidebar/layouts/search-empty', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/search-results': RouteRecordInfo<'/sidebar/layouts/search-results', '/sidebar/layouts/search-results', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-detail/': RouteRecordInfo<'/sidebar/layouts/shop-detail/', '/sidebar/layouts/shop-detail', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-detail/[id]': RouteRecordInfo<'/sidebar/layouts/shop-detail/[id]', '/sidebar/layouts/shop-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/sidebar/layouts/shop-edit': RouteRecordInfo<'/sidebar/layouts/shop-edit', '/sidebar/layouts/shop-edit', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-edit/': RouteRecordInfo<'/sidebar/layouts/shop-edit/', '/sidebar/layouts/shop-edit', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-edit/[id]': RouteRecordInfo<'/sidebar/layouts/shop-edit/[id]', '/sidebar/layouts/shop-edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/sidebar/layouts/shop-edit/experience': RouteRecordInfo<'/sidebar/layouts/shop-edit/experience', '/sidebar/layouts/shop-edit/experience', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-edit/settings': RouteRecordInfo<'/sidebar/layouts/shop-edit/settings', '/sidebar/layouts/shop-edit/settings', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-edit/skills': RouteRecordInfo<'/sidebar/layouts/shop-edit/skills', '/sidebar/layouts/shop-edit/skills', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-make': RouteRecordInfo<'/sidebar/layouts/shop-make', '/sidebar/layouts/shop-make', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-make/': RouteRecordInfo<'/sidebar/layouts/shop-make/', '/sidebar/layouts/shop-make', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-make/experience': RouteRecordInfo<'/sidebar/layouts/shop-make/experience', '/sidebar/layouts/shop-make/experience', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-make/settings': RouteRecordInfo<'/sidebar/layouts/shop-make/settings', '/sidebar/layouts/shop-make/settings', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/shop-make/skills': RouteRecordInfo<'/sidebar/layouts/shop-make/skills', '/sidebar/layouts/shop-make/skills', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/utility-account-confirm': RouteRecordInfo<'/sidebar/layouts/utility-account-confirm', '/sidebar/layouts/utility-account-confirm', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/utility-invoice': RouteRecordInfo<'/sidebar/layouts/utility-invoice', '/sidebar/layouts/utility-invoice', Record<never, never>, Record<never, never>>,
    '/sidebar/layouts/utility-promotion': RouteRecordInfo<'/sidebar/layouts/utility-promotion', '/sidebar/layouts/utility-promotion', Record<never, never>, Record<never, never>>,
    '/sidebar/maps-1': RouteRecordInfo<'/sidebar/maps-1', '/sidebar/maps-1', Record<never, never>, Record<never, never>>,
    '/sidebar/maps-2': RouteRecordInfo<'/sidebar/maps-2', '/sidebar/maps-2', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  
  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
