export function state() {
    return {
        accessToken: '',
        drawer: false,
        search: false,
        activeSlideIdx: 0,
        pinClickId: 0,
        myDeliveryList: [],
        myDeliveryCnt: 0,
        mySendingCnt: 0,
        myRouteCnt: 0,
        areaList: {},
        searchEvent: {
            code: '',
            keyword: '',
        },
        paySetting: {
            pay_minimum_price: 0,
            pay_minimum_topup: 0,
            pay_minimum_withdraw: 0,
            pay_rate: 0,
        },
        mydashboard: {
            delivery: {
                cnt_aa: 0,
                cnt_ac: 0,
                cnt_all: 0,
                cnt_cb: 0,
                cnt_ce: 0,
                cnt_df: 0,
                cnt_dp: 0,
                cnt_ds: 0,
                cnt_sp: 0,
                cnt_sr: 0,
                cnt_sw: 0,
                delivery_user: 0,
            },
            sending: {
                cnt_aa: 0,
                cnt_ac: 0,
                cnt_all: 0,
                cnt_cb: 0,
                cnt_ce: 0,
                cnt_df: 0,
                cnt_dp: 0,
                cnt_ds: 0,
                cnt_sp: 0,
                cnt_sr: 0,
                cnt_sw: 0,
                delivery_user: 0,
            }
        },
        profile: {
            account_bank: '',
            account_bank_code: '',
            account_name: '',
            account_no: '',
            account_verify_yn: '',
            avg_star: 0,
            coin: 0,
            del_yn: '',
            delivery_date: '',
            delivery_yn: '',
            dormant_yn: '',
            image_path: '',
            last_login_date: '',
            level: 0,
            marketing_yn: '',
            mod_date: '',
            nick_name: '',
            noti_ban_time: '',
            noti_yn: '',
            push_yn: '',
            reg_date: '',
            stop_yn: '',
            user: 0,
        },
        sending: {
            nick_name: '',
            c_image_path: '',
            c_nick_name: '',
            customer_user: 0,
            d_image_path: '',
            d_nick_name: '',
            delivery_comment: '',
            delivery_star: 0,
            delivery_user: 0,
            direct_pickup_yn: '',
            due_date: '',
            finish_addr: '',
            finish_addr_detail: '',
            finish_call: '',
            finish_desc: '',
            finish_name: '',
            finish_point: '',
            mission_code: '',
            id: 0,
            item_price: 0,
            item_size_code: '',
            mod_date: '',
            pickup_date: '',
            request_pickup_date: '',
            read_cnt: 0,
            read_user: 0,
            reg_date: '',
            sending_item: [],
            sending_price: 0,
            sending_talk_id: '',
            start_addr: '',
            start_addr_detail: '',
            start_desc: '',
            start_point: '',
            status_code: '',
            title: '',
            showInfoType: '',
        },
        sendingList: [],
        deviceToken: '',
        appVersion: '',
        osTypeCode: '',
        userAgent: '',
        loading: {
            loadingBus: [],
        },
        geolocation: {
            longitude: 0,
            latitude: 0,
        },
        dialogCroper: {
            active: '',
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
        },
        dialogMap: {
            active: '',
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
        },
        dialogTerms: {
            active: '',
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
        },
        dialogAlert: {
            active: '',
            title: '',
            msg: '',
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
        },
        dialogSnackbar: {
            active: '',
            title: '',
            msg: '',
            data: {},
            pin: false,
            userType: '',
            type: '',
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
        },
        dialogConfirm: {
            active: '',
            title: '',
            msg: '',
            overlay: true,
            overlayClose: true,
            positive: {
                name: '',
                click: () => { },
            },
            negative: {
                name: '',
                click: () => { },
            },
            request: {
                name: '',
                click: () => { },
            },
        },
    };
}
export const getMapPoint = (p) => {
    const point = p.match(/(\d{3}.\d+)\s(\d{2}.\d+)/g);
    return point[0].split(' ');
};
//# sourceMappingURL=state.js.map