import 'simplebar';
import '@purge-icons/generated';
import 'nprogress/nprogress.css';
import '@vueform/multiselect/themes/default.scss';
import '@vueform/slider/themes/default.scss';
import 'simplebar/dist/simplebar.css';
import 'tiny-slider/dist/tiny-slider.css';
import 'notyf/notyf.min.css';
import 'tippy.js/dist/tippy.css';
import 'tippy.js/dist/svg-arrow.css';
import 'tippy.js/dist/border.css';
import 'tippy.js/dist/backdrop.css';
import 'tippy.js/themes/light.css';
import './scss/main.scss';
//# sourceMappingURL=styles.js.map